/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les évaluations. */
        get: operations["list"];
        put?: never;
        /**
         * Crée une évaluation et génère son code.
         * @description Accessible à un agent : le pouvoir reste borné puisque la version doit être
         *     **validée** — garantie posée en base — et que l'évaluation naît fermée.
         *     Seul l'enseignant peut ensuite l'ouvrir (ADR-0003).
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'une évaluation. */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Démarre une tentative, ou reprend celle qui est en cours. */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ferme l'évaluation. **Réservé à l'enseignant.** */
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ouvre l'évaluation aux élèves. **Réservé à l'enseignant.** */
        post: operations["open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tableau de résultats d'une évaluation.
         * @description Pseudonymisé par construction : les lignes portent des jetons. La jointure
         *     avec les noms s'effectue dans le navigateur de l'enseignant, à partir de sa
         *     liste locale (ADR-0001).
         */
        get: operations["table"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{id}/results.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Même tableau en CSV, prêt pour un tableur. */
        get: operations["csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{id}/answers/{question}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Enregistre la réponse à une question. Appelé au fil de l'eau (SPEC §12). */
        put: operations["answer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Résultat d'une tentative, selon les règles de divulgation. */
        get: operations["result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remet définitivement la copie et déclenche la correction. */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Permet à un agent de vérifier que sa clé est valide et de connaître son
         *     scope, sans effet de bord.
         */
        get: operations["agent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ouvre une session enseignant. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ferme la session courante. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie que la session est valide. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentifie un participant par jeton et secret. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les groupes et leur effectif. */
        get: operations["list"];
        put?: never;
        /** Crée un groupe. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les jetons d'un groupe. Ne contient aucun nom, par construction. */
        get: operations["list_participants"];
        put?: never;
        /**
         * Crée `count` jetons dans un groupe et renvoie les secrets en clair.
         * @description Ces secrets ne seront plus jamais affichés : le navigateur de l'enseignant
         *     les joint immédiatement à sa liste nominative locale pour produire les
         *     billets (ADR-0001).
         */
        post: operations["create_participants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Détruit un groupe, ses jetons et les tentatives associées.
         * @description C'est le chemin de purge de fin d'année exigé par ADR-0002 : une opération
         *     prévue et tracée, et non un `DELETE` manuel en base.
         */
        post: operations["purge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie que l'API répond et que la base est joignable. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/join/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Présente les consignes d'une évaluation à partir de son code. */
        post: operations["join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Désactive un jeton : il ne peut plus servir à composer. */
        post: operations["deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfère un jeton vers un autre groupe.
         * @description L'échéance est recalculée sur l'année scolaire du groupe d'arrivée : un
         *     transfert ne doit pas prolonger silencieusement la durée de conservation.
         */
        post: operations["move_to_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}/reset-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Réinitialise le secret d'un jeton et renvoie le nouveau, une seule fois. */
        post: operations["reset_secret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les sujets de la banque. */
        get: operations["list"];
        put?: never;
        /** Dépose un nouveau sujet. Le résultat est **toujours un brouillon**. */
        post: operations["deposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyse un document `qcm/v1` sans rien écrire.
         * @description Le corps est du texte brut : YAML 1.2 étant un sur-ensemble de JSON, un même
         *     point d'entrée accepte les deux formats sans négociation de type.
         *
         *     Renvoie **toutes** les erreurs d'un coup : un agent qui corrige son fichier a
         *     besoin de la liste complète, pas de la première anomalie rencontrée.
         */
        post: operations["validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un sujet et de toutes ses versions. */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive ou désarchive un sujet. Réservé à l'enseignant. */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ajoute une version à un sujet existant. Elle est elle aussi un brouillon.
         * @description C'est le seul chemin de modification : une version déjà déposée est
         *     immuable, y compris en base (SPEC §5).
         */
        post: operations["add_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}/versions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document complet d'une version, tel qu'il a été déposé.
         * @description Réservé aux principaux authentifiés : il contient les bonnes réponses et les
         *     explications, qui ne doivent jamais atteindre le navigateur d'un élève
         *     (SPEC §12).
         */
        get: operations["version_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}/versions/{number}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Valide une version : `DRAFT → VALIDATED`.
         * @description **Réservé à l'enseignant.** C'est la porte de relecture humaine, et la
         *     protection réelle contre un agent qui aurait lu des instructions hostiles
         *     (ADR-0003). L'extracteur [`Teacher`] rend son contournement impossible à
         *     écrire, pas seulement déconseillé.
         */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentIdentity: {
            scope: string;
        };
        ArchiveTarget: {
            archived: boolean;
        };
        Assessment: {
            /** @description Composable à cet instant : état **et** fenêtre planifiée. */
            available: boolean;
            /** Format: date-time */
            closes_at?: string | null;
            code: string;
            correction_release: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            duration_minutes?: number | null;
            /** Format: uuid */
            group_id: string;
            group_label: string;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            max_attempts: number;
            /** Format: double */
            max_grade: number;
            mode: string;
            name: string;
            /** Format: date-time */
            opens_at?: string | null;
            score_release: string;
            shuffle_choices: boolean;
            shuffle_questions: boolean;
            state: string;
            /** Format: uuid */
            subject_id: string;
            subject_title: string;
            /** Format: int32 */
            subject_version: number;
            /** Format: double */
            total_points: number;
        };
        /**
         * @description Retour fait à l'élève, taillé selon les règles de l'évaluation.
         *
         *     Les champs absents ne sont pas masqués à l'affichage : ils ne sont pas
         *     calculés dans la réponse (SPEC §10).
         */
        AttemptResult: {
            correction?: null | components["schemas"]["Grading"];
            /** Format: double */
            grade?: number | null;
            /** Format: double */
            max_grade?: number | null;
            /** Format: double */
            max_score?: number | null;
            /** Format: double */
            percentage?: number | null;
            /** Format: double */
            score?: number | null;
            submitted: boolean;
            /** Format: date-time */
            submitted_at?: string | null;
        };
        Briefing: {
            /** Format: uuid */
            assessment_id: string;
            /**
             * Format: int32
             * @description Tentatives restantes, aménagements compris.
             */
            attempts_left: number;
            description?: string | null;
            /** Format: int32 */
            duration_minutes?: number | null;
            name: string;
            /** Format: int32 */
            question_count: number;
            /**
             * Format: uuid
             * @description Tentative déjà commencée et non remise, à reprendre.
             */
            resumable_attempt?: string | null;
            subject_title: string;
            /** Format: double */
            total_points: number;
        };
        Choice: {
            correct?: boolean;
            id: string;
            text: string;
        };
        Credentials: {
            password: string;
            username: string;
        };
        /**
         * @description Sujet déposé : identifiant, version créée, et l'URL de relecture à rendre à
         *     l'enseignant (SPEC §9).
         */
        Deposited: {
            review_url: string;
            status: string;
            /** Format: uuid */
            subject_id: string;
            summary: components["schemas"]["Summary"];
            /** Format: int32 */
            version: number;
        };
        Document: {
            metadata: components["schemas"]["Metadata"];
            questions: components["schemas"]["Question"][];
            schema: string;
        };
        Exam: {
            description?: string | null;
            questions: components["schemas"]["ExamQuestion"][];
            title: string;
            /** Format: double */
            total_points: number;
        };
        ExamChoice: {
            id: string;
            text: string;
        };
        ExamQuestion: {
            choices: components["schemas"]["ExamChoice"][];
            id: string;
            /** @description `single_choice`, `multiple_choice` ou `true_false`. */
            kind: string;
            /** @description Plusieurs réponses peuvent être cochées. */
            multiple: boolean;
            /** Format: double */
            points: number;
            prompt: string;
        };
        GivenAnswer: {
            choices: string[];
        };
        Grading: {
            /** Format: double */
            max_score: number;
            per_question: components["schemas"]["QuestionScore"][];
            /** Format: double */
            percentage: number;
            /** Format: double */
            score: number;
        };
        Group: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: int64 */
            participants: number;
            school_year: string;
        };
        Health: {
            status: string;
        };
        Identity: {
            authenticated: boolean;
        };
        /**
         * @description Jeton fraîchement créé, **secret en clair compris**.
         *
         *     C'est la seule représentation qui expose un secret, et elle n'est renvoyée
         *     qu'une fois. Le serveur n'en conserve ensuite qu'une empreinte Argon2id : il
         *     n'existe aucun moyen de réafficher ce secret, seulement de le réinitialiser.
         */
        IssuedParticipant: {
            /** Format: uuid */
            id: string;
            secret: string;
            token: string;
        };
        Metadata: {
            description?: string | null;
            subject?: string | null;
            tags?: string[];
            title: string;
        };
        /** @enum {string} */
        Mode: "exact" | "partial";
        MoveTarget: {
            /** Format: uuid */
            group_id: string;
        };
        MultipleChoice: components["schemas"]["Teaching"] & {
            choices: components["schemas"]["Choice"][];
            id: string;
            /** Format: double */
            points?: number;
            prompt: string;
            scoring?: components["schemas"]["Scoring"];
        };
        NewAssessment: {
            /** Format: date-time */
            closes_at?: string | null;
            correction_release?: components["schemas"]["Release"];
            /** Format: int32 */
            duration_minutes?: number | null;
            /** Format: uuid */
            group_id: string;
            /** Format: int32 */
            max_attempts?: number;
            /** Format: double */
            max_grade?: number;
            mode: components["schemas"]["Mode"];
            name: string;
            /** Format: date-time */
            opens_at?: string | null;
            score_release?: components["schemas"]["Release"];
            shuffle_choices?: boolean;
            shuffle_questions?: boolean;
            /** Format: uuid */
            subject_id: string;
            /**
             * Format: int32
             * @description Version du sujet. Elle doit être validée.
             */
            version: number;
        };
        NewGroup: {
            /** @description Étiquette de classe : `1SIO`, `2SIO-SLAM`. Jamais un nom de personne. */
            label: string;
            /** @description Année scolaire au format `2026-2027`. */
            school_year: string;
        };
        NewParticipants: {
            /** Format: int64 */
            count: number;
        };
        Participant: {
            active: boolean;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            id: string;
            token: string;
        };
        Purged: {
            /** Format: int64 */
            participants: number;
        };
        /**
         * @description Un enum plutôt qu'un `kind: String` accompagné de champs optionnels : les
         *     états incohérents (un `true_false` porteur de propositions, un
         *     `single_choice` doté d'un mode de notation partielle) sont inexprimables.
         */
        Question: (components["schemas"]["SingleChoice"] & {
            /** @enum {string} */
            type: "single_choice";
        }) | (components["schemas"]["MultipleChoice"] & {
            /** @enum {string} */
            type: "multiple_choice";
        }) | (components["schemas"]["TrueFalse"] & {
            /** @enum {string} */
            type: "true_false";
        });
        QuestionScore: {
            /** @description Vrai si l'élève a obtenu la totalité des points. */
            correct: boolean;
            /** Format: double */
            max_points: number;
            /** Format: double */
            points: number;
            question_id: string;
        };
        QuestionStat: {
            /**
             * Format: double
             * @description Moyenne des points obtenus, en pourcentage du barème.
             *
             *     Distincte du taux de réussite : en notation partielle, une question à
             *     85 % de moyenne et 20 % de réussite complète ne raconte pas du tout la
             *     même histoire qu'une question à 85 % des deux.
             */
            average_rate: number;
            /** Format: double */
            max_points: number;
            question_id: string;
            /**
             * Format: double
             * @description Part des copies ayant obtenu la totalité des points.
             */
            success_rate: number;
        };
        /** @enum {string} */
        Release: "IMMEDIATE" | "AFTER_CLOSE" | "NEVER";
        ResultRow: {
            /**
             * Format: int32
             * @description Nombre de copies remises.
             */
            attempts: number;
            /**
             * Format: int64
             * @description Durée de la copie retenue, en secondes.
             */
            duration_seconds?: number | null;
            /** Format: double */
            grade?: number | null;
            /** Format: double */
            max_score?: number | null;
            /** Format: uuid */
            participant_id: string;
            /** Format: double */
            percentage?: number | null;
            /** Format: double */
            score?: number | null;
            standing: components["schemas"]["Standing"];
            /** Format: date-time */
            submitted_at?: string | null;
            token: string;
        };
        ResultsTable: {
            /** Format: int32 */
            absent: number;
            /**
             * Format: double
             * @description Moyenne des notes des copies remises.
             */
            average_grade?: number | null;
            /** Format: int32 */
            in_progress: number;
            questions: components["schemas"]["QuestionStat"][];
            rows: components["schemas"]["ResultRow"][];
            /** Format: int32 */
            submitted: number;
        };
        Saved: {
            saved: boolean;
            /** Format: date-time */
            server_time: string;
        };
        Scoring: {
            mode?: components["schemas"]["Mode"];
        };
        SingleChoice: components["schemas"]["Teaching"] & {
            choices: components["schemas"]["Choice"][];
            id: string;
            /** Format: double */
            points?: number;
            prompt: string;
        };
        Sitting: {
            /** @description Réponses déjà enregistrées, pour reprendre où l'on s'était arrêté. */
            answers: {
                [key: string]: string[];
            };
            /** Format: uuid */
            attempt_id: string;
            /** Format: date-time */
            deadline?: string | null;
            exam: components["schemas"]["Exam"];
            /** Format: date-time */
            server_time: string;
        };
        /** @enum {string} */
        Standing: "SUBMITTED" | "IN_PROGRESS" | "ABSENT";
        Subject: {
            archived: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            latest_status: string;
            /** Format: int32 */
            latest_version: number;
            /** @description Titre de la version la plus récente. */
            title: string;
        };
        SubjectDetail: components["schemas"]["Subject"] & {
            versions: components["schemas"]["SubjectVersion"][];
        };
        SubjectVersion: {
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            number: number;
            /** Format: int32 */
            question_count: number;
            /** @description `DRAFT` ou `VALIDATED`. */
            status: string;
            title: string;
            /** Format: double */
            total_points: number;
            /** Format: date-time */
            validated_at?: string | null;
        };
        Summary: {
            /** Format: int32 */
            question_count: number;
            title: string;
            /** Format: double */
            total_points: number;
        };
        /**
         * @description Champs pédagogiques communs, jamais transmis au navigateur de l'élève tant
         *     que la configuration de l'évaluation n'en autorise pas la divulgation.
         */
        Teaching: {
            explanation?: string | null;
            objectives?: string[];
        };
        TokenCredentials: {
            secret: string;
            token: string;
        };
        TrueFalse: components["schemas"]["Teaching"] & {
            answer: boolean;
            id: string;
            /** Format: double */
            points?: number;
            prompt: string;
        };
        ValidationError: {
            message: string;
            /** @description Chemin dans le document, par exemple `questions[2].choices[1].id`. */
            path: string;
        };
        Verdict: {
            errors: components["schemas"]["ValidationError"][];
            summary?: null | components["schemas"]["Summary"];
            valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAssessment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description sujet, version ou groupe inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description la version n'est pas validée */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sitting"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    open: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    table: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsTable"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    csv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                question: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GivenAnswer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saved"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    result: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentIdentity"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description trop de tentatives */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenCredentials"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description groupe déjà existant */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_participants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"][];
                };
            };
        };
    };
    create_participants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewParticipants"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedParticipant"][];
                };
            };
        };
    };
    purge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purged"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Briefing"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
        };
    };
    move_to_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTarget"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
        };
    };
    reset_secret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedParticipant"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"][];
                };
            };
        };
    };
    deposit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Document qcm/v1 en YAML ou JSON */
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposited"];
                };
            };
            /** @description document invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Document qcm/v1 en YAML ou JSON */
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Verdict"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveTarget"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Document qcm/v1 en YAML ou JSON */
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposited"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    version_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectVersion"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
