/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Permet à un agent de vérifier que sa clé est valide et de connaître son
         *     scope, sans effet de bord.
         */
        get: operations["agent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ouvre une session enseignant. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ferme la session courante. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie que la session est valide. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les groupes et leur effectif. */
        get: operations["list"];
        put?: never;
        /** Crée un groupe. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les jetons d'un groupe. Ne contient aucun nom, par construction. */
        get: operations["list_participants"];
        put?: never;
        /**
         * Crée `count` jetons dans un groupe et renvoie les secrets en clair.
         * @description Ces secrets ne seront plus jamais affichés : le navigateur de l'enseignant
         *     les joint immédiatement à sa liste nominative locale pour produire les
         *     billets (ADR-0001).
         */
        post: operations["create_participants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Détruit un groupe, ses jetons et les tentatives associées.
         * @description C'est le chemin de purge de fin d'année exigé par ADR-0002 : une opération
         *     prévue et tracée, et non un `DELETE` manuel en base.
         */
        post: operations["purge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie que l'API répond et que la base est joignable. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Désactive un jeton : il ne peut plus servir à composer. */
        post: operations["deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfère un jeton vers un autre groupe.
         * @description L'échéance est recalculée sur l'année scolaire du groupe d'arrivée : un
         *     transfert ne doit pas prolonger silencieusement la durée de conservation.
         */
        post: operations["move_to_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}/reset-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Réinitialise le secret d'un jeton et renvoie le nouveau, une seule fois. */
        post: operations["reset_secret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les sujets de la banque. */
        get: operations["list"];
        put?: never;
        /** Dépose un nouveau sujet. Le résultat est **toujours un brouillon**. */
        post: operations["deposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyse un document `qcm/v1` sans rien écrire.
         * @description Le corps est du texte brut : YAML 1.2 étant un sur-ensemble de JSON, un même
         *     point d'entrée accepte les deux formats sans négociation de type.
         *
         *     Renvoie **toutes** les erreurs d'un coup : un agent qui corrige son fichier a
         *     besoin de la liste complète, pas de la première anomalie rencontrée.
         */
        post: operations["validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un sujet et de toutes ses versions. */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive ou désarchive un sujet. Réservé à l'enseignant. */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ajoute une version à un sujet existant. Elle est elle aussi un brouillon.
         * @description C'est le seul chemin de modification : une version déjà déposée est
         *     immuable, y compris en base (SPEC §5).
         */
        post: operations["add_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}/versions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document complet d'une version, tel qu'il a été déposé.
         * @description Réservé aux principaux authentifiés : il contient les bonnes réponses et les
         *     explications, qui ne doivent jamais atteindre le navigateur d'un élève
         *     (SPEC §12).
         */
        get: operations["version_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}/versions/{number}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Valide une version : `DRAFT → VALIDATED`.
         * @description **Réservé à l'enseignant.** C'est la porte de relecture humaine, et la
         *     protection réelle contre un agent qui aurait lu des instructions hostiles
         *     (ADR-0003). L'extracteur [`Teacher`] rend son contournement impossible à
         *     écrire, pas seulement déconseillé.
         */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentIdentity: {
            scope: string;
        };
        ArchiveTarget: {
            archived: boolean;
        };
        Choice: {
            correct?: boolean;
            id: string;
            text: string;
        };
        Credentials: {
            password: string;
            username: string;
        };
        /**
         * @description Sujet déposé : identifiant, version créée, et l'URL de relecture à rendre à
         *     l'enseignant (SPEC §9).
         */
        Deposited: {
            review_url: string;
            status: string;
            /** Format: uuid */
            subject_id: string;
            summary: components["schemas"]["Summary"];
            /** Format: int32 */
            version: number;
        };
        Document: {
            metadata: components["schemas"]["Metadata"];
            questions: components["schemas"]["Question"][];
            schema: string;
        };
        Group: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: int64 */
            participants: number;
            school_year: string;
        };
        Health: {
            status: string;
        };
        Identity: {
            authenticated: boolean;
        };
        /**
         * @description Jeton fraîchement créé, **secret en clair compris**.
         *
         *     C'est la seule représentation qui expose un secret, et elle n'est renvoyée
         *     qu'une fois. Le serveur n'en conserve ensuite qu'une empreinte Argon2id : il
         *     n'existe aucun moyen de réafficher ce secret, seulement de le réinitialiser.
         */
        IssuedParticipant: {
            /** Format: uuid */
            id: string;
            secret: string;
            token: string;
        };
        Metadata: {
            description?: string | null;
            subject?: string | null;
            tags?: string[];
            title: string;
        };
        /** @enum {string} */
        Mode: "exact" | "partial";
        MoveTarget: {
            /** Format: uuid */
            group_id: string;
        };
        MultipleChoice: components["schemas"]["Teaching"] & {
            choices: components["schemas"]["Choice"][];
            id: string;
            /** Format: double */
            points?: number;
            prompt: string;
            scoring?: components["schemas"]["Scoring"];
        };
        NewGroup: {
            /** @description Étiquette de classe : `1SIO`, `2SIO-SLAM`. Jamais un nom de personne. */
            label: string;
            /** @description Année scolaire au format `2026-2027`. */
            school_year: string;
        };
        NewParticipants: {
            /** Format: int64 */
            count: number;
        };
        Participant: {
            active: boolean;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            id: string;
            token: string;
        };
        Purged: {
            /** Format: int64 */
            participants: number;
        };
        /**
         * @description Un enum plutôt qu'un `kind: String` accompagné de champs optionnels : les
         *     états incohérents (un `true_false` porteur de propositions, un
         *     `single_choice` doté d'un mode de notation partielle) sont inexprimables.
         */
        Question: (components["schemas"]["SingleChoice"] & {
            /** @enum {string} */
            type: "single_choice";
        }) | (components["schemas"]["MultipleChoice"] & {
            /** @enum {string} */
            type: "multiple_choice";
        }) | (components["schemas"]["TrueFalse"] & {
            /** @enum {string} */
            type: "true_false";
        });
        Scoring: {
            mode?: components["schemas"]["Mode"];
        };
        SingleChoice: components["schemas"]["Teaching"] & {
            choices: components["schemas"]["Choice"][];
            id: string;
            /** Format: double */
            points?: number;
            prompt: string;
        };
        Subject: {
            archived: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            latest_status: string;
            /** Format: int32 */
            latest_version: number;
            /** @description Titre de la version la plus récente. */
            title: string;
        };
        SubjectDetail: components["schemas"]["Subject"] & {
            versions: components["schemas"]["SubjectVersion"][];
        };
        SubjectVersion: {
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            number: number;
            /** Format: int32 */
            question_count: number;
            /** @description `DRAFT` ou `VALIDATED`. */
            status: string;
            title: string;
            /** Format: double */
            total_points: number;
            /** Format: date-time */
            validated_at?: string | null;
        };
        Summary: {
            /** Format: int32 */
            question_count: number;
            title: string;
            /** Format: double */
            total_points: number;
        };
        /**
         * @description Champs pédagogiques communs, jamais transmis au navigateur de l'élève tant
         *     que la configuration de l'évaluation n'en autorise pas la divulgation.
         */
        Teaching: {
            explanation?: string | null;
            objectives?: string[];
        };
        TrueFalse: components["schemas"]["Teaching"] & {
            answer: boolean;
            id: string;
            /** Format: double */
            points?: number;
            prompt: string;
        };
        ValidationError: {
            message: string;
            /** @description Chemin dans le document, par exemple `questions[2].choices[1].id`. */
            path: string;
        };
        Verdict: {
            errors: components["schemas"]["ValidationError"][];
            summary?: null | components["schemas"]["Summary"];
            valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentIdentity"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description trop de tentatives */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description groupe déjà existant */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_participants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"][];
                };
            };
        };
    };
    create_participants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewParticipants"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedParticipant"][];
                };
            };
        };
    };
    purge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purged"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
        };
    };
    move_to_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTarget"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
        };
    };
    reset_secret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedParticipant"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"][];
                };
            };
        };
    };
    deposit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Document qcm/v1 en YAML ou JSON */
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposited"];
                };
            };
            /** @description document invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Document qcm/v1 en YAML ou JSON */
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Verdict"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveTarget"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Document qcm/v1 en YAML ou JSON */
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposited"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    version_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectVersion"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
